//! Runtime configuration, read from the environment.
//!
//! Everything the server needs is passed as `OTDEL_*` environment variables; the local
//! pilot keeps them in `.local/otdel.env`, which is generated by `scripts/dev-init.sh`
//! and never committed. Two rules are enforced here:
//!
//! * the server refuses to start with an empty or example secret;
//! * secrets never reach logs — `Debug` for [`Config`] redacts them, and the
//!   configuration is otherwise only read field by field.

use std::collections::BTreeMap;
use std::fmt;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::time::Duration;

use crate::error::AppError;
use crate::secret;

/// Lower bound shared by the session TTL and the idle timeout.
///
/// It is not arbitrary: `otdel.session_touch` and `otdel.session_purge_expired` raise an
/// exception below 60 seconds, so accepting a smaller value here would produce a server
/// that starts and then fails on every authenticated request.
pub const SESSION_SECONDS_MIN: u64 = 60;

/// A week. Longer than this is not a “session” for a local pilot any more.
pub const SESSION_TTL_MAX: u64 = 7 * 24 * 3600;

/// Explicit separation between the local pilot and a real deployment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuntimeEnv {
    /// Local pilot on 127.0.0.1 over plain HTTP.
    Local,
    /// Anything not the local pilot: stricter checks (secure cookies required).
    Production,
}

impl RuntimeEnv {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::Production => "production",
        }
    }

    fn parse(value: &str) -> Result<Self, AppError> {
        match value.trim().to_ascii_lowercase().as_str() {
            "local" | "development" | "dev" => Ok(Self::Local),
            "production" | "prod" => Ok(Self::Production),
            other => Err(AppError::validation(format!(
                "OTDEL_ENV must be `local` or `production`, got `{other}`"
            ))),
        }
    }
}

/// Login throttling parameters (per client address).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LoginThrottle {
    pub max_failures: u32,
    pub window: Duration,
    pub lockout: Duration,
}

#[derive(Clone)]
pub struct Config {
    pub env: RuntimeEnv,
    pub bind_addr: SocketAddr,
    /// Runtime (RLS-restricted) database role. Secret: never logged.
    pub database_url: String,
    /// Migration role. Only needed by `otdel-api migrate`. Secret: never logged.
    pub database_admin_url: Option<String>,
    pub database_max_connections: u32,
    pub bureau_slug: String,
    /// Argon2 PHC hash of the local owner password. Secret: never logged.
    pub owner_password_hash: String,
    pub storage_root: PathBuf,
    pub cors_allowed_origins: Vec<String>,
    pub session_ttl: Duration,
    pub session_idle_timeout: Duration,
    pub cookie_name: String,
    pub cookie_secure: bool,
    pub max_upload_bytes: u64,
    pub login_throttle: LoginThrottle,
    pub log_filter: String,
}

impl fmt::Debug for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Config")
            .field("env", &self.env.as_str())
            .field("bind_addr", &self.bind_addr)
            .field("database_url", &"<redacted>")
            .field(
                "database_admin_url",
                &self.database_admin_url.as_ref().map(|_| "<redacted>"),
            )
            .field("database_max_connections", &self.database_max_connections)
            .field("bureau_slug", &self.bureau_slug)
            .field("owner_password_hash", &"<redacted>")
            .field("storage_root", &self.storage_root)
            .field("cors_allowed_origins", &self.cors_allowed_origins)
            .field("session_ttl_seconds", &self.session_ttl.as_secs())
            .field(
                "session_idle_timeout_seconds",
                &self.session_idle_timeout.as_secs(),
            )
            .field("cookie_name", &self.cookie_name)
            .field("cookie_secure", &self.cookie_secure)
            .field("max_upload_bytes", &self.max_upload_bytes)
            .field("login_throttle", &self.login_throttle)
            .field("log_filter", &self.log_filter)
            .finish()
    }
}

/// Where configuration values come from. Tests use a map instead of the process env.
pub trait ConfigSource {
    fn get(&self, key: &str) -> Option<String>;
}

/// Reads `std::env`.
pub struct EnvSource;

impl ConfigSource for EnvSource {
    fn get(&self, key: &str) -> Option<String> {
        std::env::var(key).ok()
    }
}

impl ConfigSource for BTreeMap<String, String> {
    fn get(&self, key: &str) -> Option<String> {
        BTreeMap::get(self, key).cloned()
    }
}

impl Config {
    pub fn from_env() -> Result<Self, AppError> {
        Self::load(&EnvSource)
    }

    pub fn load(source: &dyn ConfigSource) -> Result<Self, AppError> {
        let env = match source.get("OTDEL_ENV") {
            Some(value) => RuntimeEnv::parse(&value)?,
            None => RuntimeEnv::Local,
        };

        let bind_addr: SocketAddr = string_or(source, "OTDEL_BIND_ADDR", "127.0.0.1:18480")
            .parse()
            .map_err(|_| {
                AppError::validation("OTDEL_BIND_ADDR must be an address like 127.0.0.1:18480")
            })?;

        let database_url = required_secret(source, "OTDEL_DATABASE_URL")?;
        let database_admin_url = match source.get("OTDEL_DATABASE_ADMIN_URL") {
            Some(value) if !value.trim().is_empty() => {
                if secret::looks_like_placeholder(&value) {
                    return Err(placeholder_error("OTDEL_DATABASE_ADMIN_URL"));
                }
                Some(value)
            }
            _ => None,
        };

        let owner_password_hash = required_secret(source, "OTDEL_OWNER_PASSWORD_HASH")?;
        if !secret::is_supported_password_hash(&owner_password_hash) {
            return Err(AppError::validation(
                "OTDEL_OWNER_PASSWORD_HASH must be an Argon2 PHC hash; \
                 run `scripts/dev-init.sh` to generate the local owner credentials",
            ));
        }

        let bureau_slug = string_or(source, "OTDEL_BUREAU_SLUG", "local");
        if bureau_slug.is_empty()
            || !bureau_slug
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        {
            return Err(AppError::validation(
                "OTDEL_BUREAU_SLUG must be lowercase ASCII letters, digits or `-`",
            ));
        }

        let storage_root = PathBuf::from(string_or(source, "OTDEL_STORAGE_ROOT", ".local/storage"));

        let cors_allowed_origins: Vec<String> = string_or(
            source,
            "OTDEL_CORS_ALLOWED_ORIGINS",
            "http://127.0.0.1:15173,http://localhost:15173",
        )
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
        .collect();
        for origin in &cors_allowed_origins {
            if origin == "*" {
                return Err(AppError::validation(
                    "OTDEL_CORS_ALLOWED_ORIGINS must list explicit origins; `*` is not allowed \
                     with credentialed requests",
                ));
            }
            if !origin.starts_with("http://") && !origin.starts_with("https://") {
                return Err(AppError::validation(format!(
                    "OTDEL_CORS_ALLOWED_ORIGINS entry `{origin}` must be a full origin, \
                     e.g. http://127.0.0.1:15173"
                )));
            }
        }

        let session_ttl = duration_secs_or(source, "OTDEL_SESSION_TTL_SECONDS", 12 * 3600)?;
        let session_idle_timeout =
            duration_secs_or(source, "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS", 2 * 3600)?;
        if session_ttl.as_secs() < SESSION_SECONDS_MIN || session_ttl.as_secs() > SESSION_TTL_MAX {
            return Err(AppError::validation(format!(
                "OTDEL_SESSION_TTL_SECONDS must be between {SESSION_SECONDS_MIN} and {SESSION_TTL_MAX}"
            )));
        }
        // The database session functions refuse an idle timeout below 60 seconds. Without
        // this check the server would start happily and then fail on every single request
        // with an opaque database error, so the same floor is enforced here.
        if session_idle_timeout.as_secs() < SESSION_SECONDS_MIN {
            return Err(AppError::validation(format!(
                "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS must be at least {SESSION_SECONDS_MIN} \
                 (the database session functions reject anything shorter)"
            )));
        }
        if session_idle_timeout > session_ttl {
            return Err(AppError::validation(
                "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS must not exceed OTDEL_SESSION_TTL_SECONDS",
            ));
        }

        let cookie_name = string_or(source, "OTDEL_SESSION_COOKIE_NAME", "otdel_session");
        if cookie_name.is_empty()
            || !cookie_name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        {
            return Err(AppError::validation(
                "OTDEL_SESSION_COOKIE_NAME must be alphanumeric with `_`/`-`",
            ));
        }

        let cookie_secure = match source.get("OTDEL_COOKIE_SECURE") {
            Some(value) => parse_bool(&value, "OTDEL_COOKIE_SECURE")?,
            None => env == RuntimeEnv::Production,
        };
        if env == RuntimeEnv::Production && !cookie_secure {
            return Err(AppError::validation(
                "OTDEL_COOKIE_SECURE cannot be disabled when OTDEL_ENV=production",
            ));
        }

        let max_upload_bytes = parse_u64_or(source, "OTDEL_MAX_UPLOAD_BYTES", 25 * 1024 * 1024)?;
        if max_upload_bytes == 0 || max_upload_bytes > 512 * 1024 * 1024 {
            return Err(AppError::validation(
                "OTDEL_MAX_UPLOAD_BYTES must be between 1 and 536870912",
            ));
        }

        let login_throttle = LoginThrottle {
            max_failures: u32::try_from(parse_u64_or(source, "OTDEL_LOGIN_MAX_FAILURES", 10)?)
                .map_err(|_| AppError::validation("OTDEL_LOGIN_MAX_FAILURES is too large"))?
                .max(1),
            window: duration_secs_or(source, "OTDEL_LOGIN_FAILURE_WINDOW_SECONDS", 900)?,
            lockout: duration_secs_or(source, "OTDEL_LOGIN_LOCKOUT_SECONDS", 900)?,
        };

        let database_max_connections =
            u32::try_from(parse_u64_or(source, "OTDEL_DATABASE_MAX_CONNECTIONS", 8)?)
                .map_err(|_| AppError::validation("OTDEL_DATABASE_MAX_CONNECTIONS is too large"))?
                .clamp(1, 64);

        let log_filter = string_or(source, "OTDEL_LOG", "info,otdel_api=info,sqlx=warn");

        Ok(Self {
            env,
            bind_addr,
            database_url,
            database_admin_url,
            database_max_connections,
            bureau_slug,
            owner_password_hash,
            storage_root,
            cors_allowed_origins,
            session_ttl,
            session_idle_timeout,
            cookie_name,
            cookie_secure,
            max_upload_bytes,
            login_throttle,
            log_filter,
        })
    }

    /// Admin URL or a clear error explaining which variable is missing.
    pub fn require_admin_database_url(&self) -> Result<&str, AppError> {
        self.database_admin_url.as_deref().ok_or_else(|| {
            AppError::validation(
                "OTDEL_DATABASE_ADMIN_URL is required for migrations (migrations run as the \
                 owning role, never as the RLS-restricted runtime role)",
            )
        })
    }
}

fn string_or(source: &dyn ConfigSource, key: &str, default: &str) -> String {
    match source.get(key) {
        Some(value) if !value.trim().is_empty() => value.trim().to_owned(),
        _ => default.to_owned(),
    }
}

fn required_secret(source: &dyn ConfigSource, key: &str) -> Result<String, AppError> {
    let value = source
        .get(key)
        .ok_or_else(|| AppError::validation(format!("{key} is not set")))?;
    if secret::looks_like_placeholder(&value) {
        return Err(placeholder_error(key));
    }
    Ok(value)
}

fn placeholder_error(key: &str) -> AppError {
    AppError::validation(format!(
        "{key} still contains an empty or example value; generate local credentials with \
         `scripts/dev-init.sh` (the server refuses to start with a known placeholder)"
    ))
}

fn parse_bool(value: &str, key: &str) -> Result<bool, AppError> {
    match value.trim().to_ascii_lowercase().as_str() {
        "1" | "true" | "yes" | "on" => Ok(true),
        "0" | "false" | "no" | "off" => Ok(false),
        _ => Err(AppError::validation(format!("{key} must be true or false"))),
    }
}

fn parse_u64_or(source: &dyn ConfigSource, key: &str, default: u64) -> Result<u64, AppError> {
    match source.get(key) {
        Some(value) if !value.trim().is_empty() => value
            .trim()
            .parse()
            .map_err(|_| AppError::validation(format!("{key} must be a non-negative integer"))),
        _ => Ok(default),
    }
}

fn duration_secs_or(
    source: &dyn ConfigSource,
    key: &str,
    default: u64,
) -> Result<Duration, AppError> {
    Ok(Duration::from_secs(parse_u64_or(source, key, default)?))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_env() -> BTreeMap<String, String> {
        let hash = secret::hash_password("local-owner-password").unwrap();
        BTreeMap::from([
            (
                "OTDEL_DATABASE_URL".to_owned(),
                "postgres://otdel_app:s3cr3t@127.0.0.1:58432/otdel".to_owned(),
            ),
            ("OTDEL_OWNER_PASSWORD_HASH".to_owned(), hash),
        ])
    }

    #[test]
    fn defaults_match_the_local_pilot_contract() {
        let config = Config::load(&base_env()).unwrap();
        assert_eq!(config.env, RuntimeEnv::Local);
        assert_eq!(config.bind_addr.to_string(), "127.0.0.1:18480");
        assert_eq!(config.max_upload_bytes, 25 * 1024 * 1024);
        assert_eq!(config.session_ttl, Duration::from_secs(12 * 3600));
        assert!(!config.cookie_secure);
        assert_eq!(
            config.cors_allowed_origins,
            vec![
                "http://127.0.0.1:15173".to_owned(),
                "http://localhost:15173".to_owned()
            ]
        );
    }

    #[test]
    fn refuses_missing_and_placeholder_secrets() {
        let mut env = base_env();
        env.remove("OTDEL_DATABASE_URL");
        assert!(Config::load(&env).is_err());

        let mut env = base_env();
        env.insert(
            "OTDEL_DATABASE_URL".to_owned(),
            "postgres://otdel:changeme@localhost:5432/otdel_dev".to_owned(),
        );
        let error = Config::load(&env).unwrap_err();
        assert!(error.message.contains("OTDEL_DATABASE_URL"));

        let mut env = base_env();
        env.insert("OTDEL_OWNER_PASSWORD_HASH".to_owned(), String::new());
        assert!(Config::load(&env).is_err());

        let mut env = base_env();
        env.insert(
            "OTDEL_OWNER_PASSWORD_HASH".to_owned(),
            "plaintext-password".to_owned(),
        );
        assert!(Config::load(&env).is_err());
    }

    #[test]
    fn session_timings_respect_the_database_floor() {
        let mut env = base_env();

        // Below the floor the database functions reject every request, so startup fails.
        for seconds in ["0", "1", "59"] {
            env.insert(
                "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS".to_owned(),
                seconds.to_owned(),
            );
            let error = Config::load(&env).unwrap_err();
            assert!(
                error.message.contains("OTDEL_SESSION_IDLE_TIMEOUT_SECONDS"),
                "unexpected error for {seconds}s: {}",
                error.message
            );
        }

        // Exactly the floor is accepted.
        env.insert(
            "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS".to_owned(),
            SESSION_SECONDS_MIN.to_string(),
        );
        let config = Config::load(&env).unwrap();
        assert_eq!(
            config.session_idle_timeout,
            Duration::from_secs(SESSION_SECONDS_MIN)
        );

        // The same floor applies to the absolute TTL, and the idle timeout may not exceed it.
        env.insert("OTDEL_SESSION_TTL_SECONDS".to_owned(), "59".to_owned());
        assert!(Config::load(&env).is_err());

        env.insert("OTDEL_SESSION_TTL_SECONDS".to_owned(), "120".to_owned());
        env.insert(
            "OTDEL_SESSION_IDLE_TIMEOUT_SECONDS".to_owned(),
            "121".to_owned(),
        );
        assert!(Config::load(&env).is_err());

        env.insert(
            "OTDEL_SESSION_TTL_SECONDS".to_owned(),
            (SESSION_TTL_MAX + 1).to_string(),
        );
        assert!(Config::load(&env).is_err());
    }

    #[test]
    fn production_requires_secure_cookies() {
        let mut env = base_env();
        env.insert("OTDEL_ENV".to_owned(), "production".to_owned());
        assert!(Config::load(&env).unwrap().cookie_secure);

        env.insert("OTDEL_COOKIE_SECURE".to_owned(), "false".to_owned());
        assert!(Config::load(&env).is_err());
    }

    #[test]
    fn wildcard_origin_is_rejected() {
        let mut env = base_env();
        env.insert("OTDEL_CORS_ALLOWED_ORIGINS".to_owned(), "*".to_owned());
        assert!(Config::load(&env).is_err());

        env.insert(
            "OTDEL_CORS_ALLOWED_ORIGINS".to_owned(),
            "127.0.0.1:15173".to_owned(),
        );
        assert!(Config::load(&env).is_err());
    }

    #[test]
    fn debug_output_never_contains_secrets() {
        let config = Config::load(&base_env()).unwrap();
        let rendered = format!("{config:?}");
        assert!(!rendered.contains("s3cr3t"));
        assert!(!rendered.contains(&config.owner_password_hash));
        assert!(rendered.contains("<redacted>"));
    }
}
