#!/usr/bin/env bash
# Generate the local credentials and environment for the OTDEL block 1 pilot.
#
# Everything it writes lands in .local/ (git-ignored, never committed):
#
#   .local/db.env             — PostgreSQL container credentials (compose env_file)
#   .local/otdel.env          — application environment (DB URLs, password hash, paths)
#   .local/owner-password.txt — the generated owner password, mode 0600
#
# The password is written to that file and is **not** printed: a terminal scrollback, a
# CI log or a screen recording must not end up holding it. Read it with
#   cat .local/owner-password.txt
#
# Two details that are easy to get wrong and are handled deliberately here:
#
#   * entropy comes from python3's `secrets` module, not from `tr < /dev/urandom | head`
#     — that pipeline dies with SIGPIPE (exit 141) under `set -o pipefail`;
#   * every value written to .local/otdel.env is shell-quoted, because the Argon2 PHC
#     hash contains `$argon2id$v=19$...`, which an unquoted `source` would expand away.
#
# Re-running keeps existing files unless --force is given, so it cannot silently
# invalidate a database that was already initialised with the old passwords.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

force=0
if [[ "${1:-}" == "--force" ]]; then
    force=1
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "dev-init: python3 is required (used for entropy and safe file writing)." >&2
    exit 1
fi

cargo_bin="${CARGO:-cargo}"
if ! command -v "$cargo_bin" >/dev/null 2>&1; then
    echo "dev-init: cargo not found in PATH; install the Rust toolchain first." >&2
    exit 1
fi

mkdir -p .local
chmod 700 .local

if [[ -f .local/otdel.env && $force -eq 0 ]]; then
    echo "dev-init: .local/otdel.env already exists; nothing regenerated."
    echo "dev-init: pass --force to replace it (this invalidates the roles already in the database)."
    exit 0
fi

umask 077

# --- entropy --------------------------------------------------------------------
# Hex only: these values also appear inside connection URLs, where a random
# punctuation character would have to be percent-encoded.
hex_secret() {
    python3 -c 'import secrets; print(secrets.token_hex(24))'
}
# Alphanumeric: the owner types this one.
alnum_password() {
    python3 - <<'PY'
import secrets
import string
alphabet = string.ascii_letters + string.digits
print("".join(secrets.choice(alphabet) for _ in range(28)))
PY
}

superuser_password="$(hex_secret)"
migrator_password="$(hex_secret)"
app_password="$(hex_secret)"
owner_password="$(alnum_password)"

# --- password hash ---------------------------------------------------------------
# The password goes to the binary over stdin, never as an argument (arguments are
# visible to every process on the machine through `ps`).
echo "dev-init: building otdel-api to hash the owner password (the first run takes a while)..."
"$cargo_bin" build --quiet --bin otdel-api
owner_password_hash="$(printf '%s' "$owner_password" | ./target/debug/otdel-api hash-password)"

if [[ -z "$owner_password_hash" ]]; then
    echo "dev-init: could not hash the owner password." >&2
    exit 1
fi

# --- .local/db.env (read by docker compose) ---------------------------------------
# Hex values only, so compose's own parser needs no quoting rules.
cat > .local/db.env <<EOF
# Generated by scripts/dev-init.sh — local only, never commit.
POSTGRES_USER=otdel_superuser
POSTGRES_PASSWORD=${superuser_password}
OTDEL_MIGRATOR_PASSWORD=${migrator_password}
OTDEL_APP_PASSWORD=${app_password}
EOF
chmod 600 .local/db.env

# --- .local/otdel.env (sourced by the shell) ---------------------------------------
# Written by python3 with shlex.quote on every value. Values are passed through the
# environment rather than argv so they never show up in `ps`.
OTDEL_INIT_APP_PASSWORD="$app_password" \
OTDEL_INIT_MIGRATOR_PASSWORD="$migrator_password" \
OTDEL_INIT_OWNER_HASH="$owner_password_hash" \
OTDEL_INIT_REPO_ROOT="$repo_root" \
python3 - <<'PY'
import os
import shlex

app_password = os.environ["OTDEL_INIT_APP_PASSWORD"]
migrator_password = os.environ["OTDEL_INIT_MIGRATOR_PASSWORD"]
owner_hash = os.environ["OTDEL_INIT_OWNER_HASH"]
repo_root = os.environ["OTDEL_INIT_REPO_ROOT"]

values = [
    ("OTDEL_ENV", "local"),
    ("OTDEL_BIND_ADDR", "127.0.0.1:18480"),
    # Runtime role: restricted, row-level security applies to it.
    ("OTDEL_DATABASE_URL", f"postgres://otdel_app:{app_password}@127.0.0.1:58432/otdel"),
    # Migration role: used only by `otdel-api migrate` / `otdel-api bootstrap`.
    (
        "OTDEL_DATABASE_ADMIN_URL",
        f"postgres://otdel_migrator:{migrator_password}@127.0.0.1:58432/otdel",
    ),
    ("OTDEL_DATABASE_MAX_CONNECTIONS", "8"),
    ("OTDEL_BUREAU_SLUG", "local"),
    ("OTDEL_OWNER_PASSWORD_HASH", owner_hash),
    ("OTDEL_STORAGE_ROOT", os.path.join(repo_root, ".local", "storage")),
    (
        "OTDEL_CORS_ALLOWED_ORIGINS",
        "http://127.0.0.1:15173,http://localhost:15173",
    ),
    ("OTDEL_SESSION_TTL_SECONDS", "43200"),
    ("OTDEL_SESSION_IDLE_TIMEOUT_SECONDS", "7200"),
    ("OTDEL_SESSION_COOKIE_NAME", "otdel_session"),
    ("OTDEL_COOKIE_SECURE", "false"),
    ("OTDEL_MAX_UPLOAD_BYTES", "26214400"),
    ("OTDEL_LOGIN_MAX_FAILURES", "10"),
    ("OTDEL_LOGIN_FAILURE_WINDOW_SECONDS", "900"),
    ("OTDEL_LOGIN_LOCKOUT_SECONDS", "900"),
    ("OTDEL_LOG", "info,otdel_api=info,otdel_worker=info,sqlx=warn"),
]

lines = [
    "# Generated by scripts/dev-init.sh — local only, never commit.",
    "# Load it with: set -a; . ./.local/otdel.env; set +a   (or use scripts/dev-api.sh)",
    "# Every value is shell-quoted: the Argon2 hash contains `$` and must not be expanded.",
    "",
]
lines += [f"{name}={shlex.quote(value)}" for name, value in values]

with open(".local/otdel.env", "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
PY
chmod 600 .local/otdel.env

printf '%s\n' "$owner_password" > .local/owner-password.txt
chmod 600 .local/owner-password.txt

mkdir -p .local/storage
chmod 700 .local/storage

# --- verification ------------------------------------------------------------------
# Re-read the generated file exactly the way the run scripts do and confirm the hash
# survived quoting. Only digests are compared, so no secret is printed.
reloaded_digest="$(
    set -a
    # shellcheck disable=SC1091
    . ./.local/otdel.env
    set +a
    printf '%s' "${OTDEL_OWNER_PASSWORD_HASH:-}" | python3 -c \
        'import hashlib,sys; sys.stdout.write(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())'
)"
expected_digest="$(printf '%s' "$owner_password_hash" | python3 -c \
    'import hashlib,sys; sys.stdout.write(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())')"

if [[ "$reloaded_digest" != "$expected_digest" ]]; then
    echo "dev-init: the generated environment does not reload correctly (password hash changed)." >&2
    exit 1
fi

# The application's own validation is the final word on whether this env is usable.
if ! (
    set -a
    # shellcheck disable=SC1091
    . ./.local/otdel.env
    set +a
    ./target/debug/otdel-api check-config >/dev/null
); then
    echo "dev-init: the generated environment failed otdel-api check-config." >&2
    exit 1
fi

echo "dev-init: wrote .local/db.env, .local/otdel.env, .local/owner-password.txt (mode 0600)."
echo "dev-init: environment verified (reload + otdel-api check-config)."
echo "dev-init: the owner password was NOT printed — read it with: cat .local/owner-password.txt"
echo "dev-init: next: make db-up && make migrate && make bootstrap && make server"
