#!/usr/bin/env bash
# R05 live environment — the productologist UAT against real partner catalogues.
#
# Usage:
#   scripts/r05-live.sh init                 generate .local/r05-live/* (idempotent)
#   scripts/r05-live.sh up|down              start/stop the isolated PostgreSQL container
#   scripts/r05-live.sh migrate|bootstrap    apply migrations / provision the bureau
#   scripts/r05-live.sh serve                run the API on 127.0.0.1:18481
#   scripts/r05-live.sh worker [run|once|probe]
#   scripts/r05-live.sh psql [args…]         psql into otdel_r05_live as the migration role
#
# Isolation, stated once and enforced everywhere below:
#
#   database   otdel_r05_live           (never `otdel`, never `otdel_test`)
#   port       127.0.0.1:58433          (the pilot keeps 58432)
#   volume     otdel-r05-live-pgdata    (its own storage)
#   storage    .local/r05-live/storage  (its own uploaded-material root)
#   API port   127.0.0.1:18481          (the pilot keeps 18480)
#
# The model key is NEVER written into this repository's files. It is read, in-shell only,
# from an existing git-ignored file named by OTDEL_R05_LLM_ENV (see `llm_env` below) and
# exported into the child process. It is never echoed, never copied and never stored in
# .local/r05-live/otdel.env.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

env_dir=".local/r05-live"
compose_file="infra/r05-live/compose.yaml"
COMPOSE=${COMPOSE:-docker compose}

# --- environment ------------------------------------------------------------------

load_env() {
    if [[ ! -f "$env_dir/otdel.env" ]]; then
        echo "r05-live: $env_dir/otdel.env is missing; run scripts/r05-live.sh init first." >&2
        exit 1
    fi
    set -a
    # shellcheck disable=SC1090
    . "./$env_dir/otdel.env"
    set +a
}

# Export the model settings from the owner's own git-ignored key file, without printing
# them. Absent file → the roles stay unconfigured, which the application reports as a
# state rather than failing.
load_llm() {
    local file="${OTDEL_R05_LLM_ENV:-}"
    if [[ -z "$file" ]]; then
        echo "r05-live: OTDEL_R05_LLM_ENV is not set; the model adapter stays unconfigured." >&2
        return 0
    fi
    if [[ ! -f "$file" ]]; then
        echo "r05-live: OTDEL_R05_LLM_ENV points at a file that does not exist." >&2
        exit 1
    fi
    set -a
    # shellcheck disable=SC1090
    . "$file"
    set +a
    # Overrides applied after the file, so the run's own bounds always win.
    [[ -n "${OTDEL_R05_MODEL:-}" ]] && export OTDEL_LLM_MODEL="$OTDEL_R05_MODEL"
    return 0
}

init() {
    if [[ -f "$env_dir/otdel.env" && "${1:-}" != "--force" ]]; then
        echo "r05-live: $env_dir/otdel.env already exists; pass --force to regenerate."
        return 0
    fi

    mkdir -p "$env_dir"
    chmod 700 .local "$env_dir"
    umask 077

    local superuser_password migrator_password app_password owner_password
    superuser_password="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
    migrator_password="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
    app_password="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
    owner_password="$(python3 - <<'PY'
import secrets, string
alphabet = string.ascii_letters + string.digits
print("".join(secrets.choice(alphabet) for _ in range(28)))
PY
)"

    cargo build --quiet --bin otdel-api
    local owner_hash
    owner_hash="$(printf '%s' "$owner_password" | ./target/debug/otdel-api hash-password)"
    if [[ -z "$owner_hash" ]]; then
        echo "r05-live: could not hash the owner password." >&2
        exit 1
    fi

    cat > "$env_dir/db.env" <<EOF
# Generated by scripts/r05-live.sh — local only, never commit.
POSTGRES_USER=otdel_superuser
POSTGRES_PASSWORD=${superuser_password}
OTDEL_MIGRATOR_PASSWORD=${migrator_password}
OTDEL_APP_PASSWORD=${app_password}
EOF
    chmod 600 "$env_dir/db.env"

    OTDEL_INIT_APP_PASSWORD="$app_password" \
    OTDEL_INIT_MIGRATOR_PASSWORD="$migrator_password" \
    OTDEL_INIT_OWNER_HASH="$owner_hash" \
    OTDEL_INIT_REPO_ROOT="$repo_root" \
    python3 - <<'PY'
import os
import shlex

app_password = os.environ["OTDEL_INIT_APP_PASSWORD"]
migrator_password = os.environ["OTDEL_INIT_MIGRATOR_PASSWORD"]
owner_hash = os.environ["OTDEL_INIT_OWNER_HASH"]
repo_root = os.environ["OTDEL_INIT_REPO_ROOT"]

host = "127.0.0.1:58433"
database = "otdel_r05_live"

values = [
    ("OTDEL_ENV", "local"),
    ("OTDEL_BIND_ADDR", "127.0.0.1:18481"),
    ("OTDEL_DATABASE_URL", f"postgres://otdel_app:{app_password}@{host}/{database}"),
    (
        "OTDEL_DATABASE_ADMIN_URL",
        f"postgres://otdel_migrator:{migrator_password}@{host}/{database}",
    ),
    ("OTDEL_DATABASE_MAX_CONNECTIONS", "8"),
    ("OTDEL_BUREAU_SLUG", "r05-live"),
    ("OTDEL_OWNER_PASSWORD_HASH", owner_hash),
    ("OTDEL_STORAGE_ROOT", os.path.join(repo_root, ".local", "r05-live", "storage")),
    ("OTDEL_CORS_ALLOWED_ORIGINS", "http://127.0.0.1:15173,http://localhost:15173"),
    ("OTDEL_SESSION_TTL_SECONDS", "43200"),
    ("OTDEL_SESSION_IDLE_TIMEOUT_SECONDS", "7200"),
    ("OTDEL_SESSION_COOKIE_NAME", "otdel_session"),
    ("OTDEL_COOKIE_SECURE", "false"),
    ("OTDEL_MAX_UPLOAD_BYTES", "26214400"),
    ("OTDEL_LOGIN_MAX_FAILURES", "10"),
    ("OTDEL_LOGIN_FAILURE_WINDOW_SECONDS", "900"),
    ("OTDEL_LOGIN_LOCKOUT_SECONDS", "900"),
    ("OTDEL_LOG", "info,otdel_api=info,otdel_worker=info,sqlx=warn"),
]

lines = [
    "# Generated by scripts/r05-live.sh — local only, never commit.",
    "# The model key is NOT here: it is sourced in-shell from OTDEL_R05_LLM_ENV.",
    "",
] + [f"{name}={shlex.quote(value)}" for name, value in values]

with open(os.path.join(".local", "r05-live", "otdel.env"), "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
PY
    chmod 600 "$env_dir/otdel.env"

    printf '%s\n' "$owner_password" > "$env_dir/owner-password.txt"
    chmod 600 "$env_dir/owner-password.txt"
    mkdir -p "$env_dir/storage"
    chmod 700 "$env_dir/storage"

    echo "r05-live: wrote $env_dir/{db.env,otdel.env,owner-password.txt} (mode 0600)."
    echo "r05-live: the owner password was NOT printed — read it with: cat $env_dir/owner-password.txt"
}

command="${1:-}"
shift || true

case "$command" in
    init)
        init "${1:-}"
        ;;
    up)
        $COMPOSE -f "$compose_file" up -d postgres
        ;;
    down)
        $COMPOSE -f "$compose_file" stop postgres
        ;;
    logs)
        $COMPOSE -f "$compose_file" logs --tail 50 postgres
        ;;
    migrate|bootstrap|check-config|serve)
        load_env
        load_llm
        exec cargo run --quiet --bin otdel-api -- "$command"
        ;;
    worker)
        load_env
        load_llm
        exec cargo run --quiet --bin otdel-worker -- "${1:-once}"
        ;;
    psql)
        load_env
        exec docker exec -i otdel-r05-live-postgres \
            psql --quiet --no-psqlrc --set ON_ERROR_STOP=1 \
                 --username otdel_superuser --dbname otdel_r05_live "$@"
        ;;
    *)
        sed -n '2,30p' "$0"
        exit 1
        ;;
esac
