#!/bin/bash
# Runs once, on first initialisation of the PostgreSQL data directory (the official
# entrypoint executes everything in /docker-entrypoint-initdb.d as the superuser).
#
# It creates the two roles the application design depends on:
#
#   otdel_migrator — owns the schema, applies migrations. NOT used by the API.
#   otdel_app      — runtime role: no ownership, NOSUPERUSER, NOBYPASSRLS,
#                    NOCREATEDB, NOCREATEROLE. Row-level security applies to it,
#                    and the API refuses to start as any role that fails that check.
#
# Passwords come from the environment (.local/db.env, generated by scripts/dev-init.sh)
# and are never echoed: `set -x` stays off and psql runs quietly.

set -euo pipefail

: "${OTDEL_MIGRATOR_PASSWORD:?OTDEL_MIGRATOR_PASSWORD must be set (see scripts/dev-init.sh)}"
: "${OTDEL_APP_PASSWORD:?OTDEL_APP_PASSWORD must be set (see scripts/dev-init.sh)}"

psql --quiet --no-psqlrc --set ON_ERROR_STOP=1 \
     --username "$POSTGRES_USER" --dbname otdel \
     --set migrator_password="$OTDEL_MIGRATOR_PASSWORD" \
     --set app_password="$OTDEL_APP_PASSWORD" <<'SQL'
CREATE ROLE otdel_migrator LOGIN PASSWORD :'migrator_password'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS NOINHERIT;

CREATE ROLE otdel_app LOGIN PASSWORD :'app_password'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS NOINHERIT;

-- The migration role owns the database objects it creates.
ALTER DATABASE otdel OWNER TO otdel_migrator;

-- Nothing is reachable by default; the migration grants exactly what the API needs.
REVOKE ALL ON DATABASE otdel FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE otdel TO otdel_migrator, otdel_app;
GRANT USAGE ON SCHEMA public TO otdel_migrator;

-- Keep the `otdel.*` custom settings that row-level security reads from being
-- settable by anything but a session that already connected as one of these roles.
ALTER ROLE otdel_app SET search_path = otdel, public;
ALTER ROLE otdel_migrator SET search_path = otdel, public;
SQL

echo "otdel: created roles otdel_migrator and otdel_app"
